### ISSUE TITLE
codefresh_pipeline: project_id always marked as changed

### ISSUE THREAD

**Issue by gnarea** [codefresh-io/terraform-provider-codefresh#21] opened 2020-11-09 21:42 UTC
```
  # module.gw_test_cd.codefresh_pipeline.test will be updated in-place
  ~ resource "codefresh_pipeline" "test" {
        id         = "<THE-ID>"
        name       = "cloud-gateway/vault-test"
      - project_id = "<THE-PROJECT-ID>" -> null
        revision   = 5

(...)
```

**Comment by sandrogattuso** [comment] 2021-02-03 22:26
Duplicate of #11

**Comment by korenyoni** [comment] 2024-01-16 06:43
Old issue but tested anyways — can no longer reproduce:

```bash
...
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

codefresh_project.test: Creating...
codefresh_project.test: Creation complete after 0s [id=65a6254bb765746520a68d1c]
codefresh_pipeline.test: Creating...
codefresh_pipeline.test: Creation complete after 1s [id=65a6254bb7657419a0a68d1f]

Apply complete! Resources: 2 added, 0 changed, 0 destroyed.

Outputs:

id = "65a6254bb7657419a0a68d1f"
$ terraform apply
╷
│ Warning: Provider development overrides are in effect
│
│ The following provider development overrides are set in the CLI configuration:
│  - codefresh-io/codefresh in /Users/yonatankoren/software/codefresh-io/terraform-provider-codefresh
│
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
codefresh_project.test: Refreshing state... [id=65a6254bb765746520a68d1c]
codefresh_pipeline.test: Refreshing state... [id=65a6254bb7657419a0a68d1f]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

id = "65a6254bb7657419a0a68d1f"
```

**Closed by korenyoni** 2024-01-16 06:43 UTC
